# See here for image contents: https://github.com/microsoft/vscode-dev-containers/blob/v0.202.3/containers/python-3/.devcontainer/base.Dockerfile
# [Choice] Python version (use -bullseye variants on local arm64/Apple Silicon): 3, 3.9, 3.8, 3.7, 3.6, 3-bullseye, 3.9-bullseye, 3.8-bullseye, 3.7-bullseye, 3.6-bullseye, 3-buster, 3.9-buster, 3.8-buster, 3.7-buster, 3.6-buster
ARG VARIANT=3.9-bullseye
FROM mcr.microsoft.com/devcontainers/python:${VARIANT}

# [Optional] Allow the vscode user to pip install globally w/o sudo
# ENV PIP_GLOBAL=/usr/local/pip-global
# ENV PYTHONPATH=${PIP_GLOBAL}:${PYTHONPATH}
# ENV PATH=${PIP_GLOBAL}/bin:${PATH}
# RUN if ! cat /etc/group | grep -e "^pip-global:" > /dev/null 2>&1; then groupadd -r pip-global; fi \
#     && usermod -a -G pip-global vscode \
#     && umask 0002 && mkdir -p ${PIP_GLOBAL} \
#     && chown :pip-global ${PIP_GLOBAL} \
#     && ( [ ! -f "/etc/profile.d/00-restore-env.sh" ] || sed -i -e "s/export PATH=/export PATH=\/usr\/local\/pip-global:/" /etc/profile.d/00-restore-env.sh )

# [Choice] Node.js version: none, lts/*, 16, 14, 12, 10
ARG NODE_VERSION="none"
RUN if [ "${NODE_VERSION}" != "none" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi

# Base requirements
COPY .devcontainer/requirements.txt /tmp/pip-tmp/
RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
   && rm -rf /tmp/pip-tmp

ARG POETRY_CACHE_DIR='/root/.cache/poetry'
COPY pyproject.toml poetry.lock ./
RUN \
  --mount=type=cache,target=${POETRY_CACHE_DIR} \
  poetry config cache-dir ${POETRY_CACHE_DIR} && \
  poetry config installer.parallel false && \
  poetry config virtualenvs.create false && \ 
  poetry install --no-interaction && \
  rm pyproject.toml poetry.lock

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1